### ISSUE TITLE
Add level support

### ISSUE THREAD

**Issue by diaboloshogunate** [diaboloshogunate/transmission#21]
when finishing the a level try to load the next level.

I am thinking that we have a directory in scenes with the different levels numbered. After finishing the level try to load the next one. if it doesn't exist show a winning screen instead.

**Comment by sirslade** [comment]
It doesn't look like there's support to load from directory. Probably the best option would be to have a strin var for 'nextLevelName' on the exit door and call LoadLevel(nextLevelName)

Alternatively we could get the build index for the scene and increment it by 1 for the next load level.
